#!/bin/sh

#echo ${*} > /tmp/args.txt
#cat > /tmp/stdin.txt
set -x
#ssh -o StrictHostKeyChecking=no racedb@qllabels.local QLLABELS.sh ${1}
ssh -o StrictHostKeyChecking=no racedb@qllabels.local QLLABELS.py ${1}
