
version: '3.8'

services:

    qlmux_proxy:
        image: ${IMAGE}
        privileged: true
        cap_add:
            - NET_ADMIN # Allows the container to manage network interfaces
            - NET_RAW   # Allows the container to create raw sockets
        container_name: ${CONTAINER}
        hostname: ${HOSTNAME}
        restart: always
        network_mode: host
        environment:
            PYTHONUNBUFFERED: 1
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro

