
version: '3.4'

services:

    qlmux_proxy:
        image: qlmux_proxy:private
        container_name: ${CONTAINER_NAME}
        hostname: qlmux_proxy.local
        restart: always
        network_mode: host
        environment:
            PYTHONUNBUFFERED: 1
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro

