
version: '3.8'

services:

    qlmux_proxy:
        image: ${IMAGE}
        container_name: ${CONTAINER}
        hostname: ${HOSTNAME}
        restart: always
        network_mode: host
        environment:
            PYTHONUNBUFFERED: 1
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro

