version: '3.8'

services:
  dnsmasq:
    image: andyshinn/dnsmasq:2.85
    container_name: dnsmasq
    env_file:
      - ./docker.env
    volumes:
      - ./hosts.txt:/etc/dnsmasq.d/hosts.conf:ro
    command:
      - --no-resolv
      - --server=${DNSSERVERS}
      - --addn-hosts=/etc/dnsmasq.d/hosts.conf
      - --log-facility=/var/log/dnsmasq.log
      - --log-queries
    ports:
      - "53:53/udp"
    restart: unless-stopped

